<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <PluginGuid>6f79690c-c1d0-4738-b241-09aaa2c570e7</PluginGuid>
    <Description>Independent danmuku management for Jellyfin.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" ExcludeAssets="runtime" />
    <EmbeddedResource Include="Configuration/configPage.html" />
  </ItemGroup>
</Project>
