<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>0.1.0</Version>
    <AssemblyVersion>0.1.0.0</AssemblyVersion>
    <PluginGuid>6f79690c-c1d0-4738-b241-09aaa2c570e7</PluginGuid>
    <Description>Independent danmuku management for Jellyfin.</Description>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Jellyfin.Controller" Version="12.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="12.1.0" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <EmbeddedResource Include="Configuration/configPage.html" />
    <EmbeddedResource Include="Web/bootstrap.js">
      <LogicalName>Jellyfin.Plugin.Danmuku.Web.bootstrap.js</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Web/danmuku.js">
      <LogicalName>Jellyfin.Plugin.Danmuku.Web.danmuku.js</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="Web/danmuku.css">
      <LogicalName>Jellyfin.Plugin.Danmuku.Web.danmuku.css</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
</Project>
